# Generated by Django 3.0.5 on 2020-04-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='disease',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
