# Generated by Django 3.0.5 on 2020-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200419_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='disease',
            new_name='type',
        ),
    ]
