# Generated by Django 3.0.5 on 2020-04-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_decisiontree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionTree',
        ),
    ]
